name: Wait for Vercel
description: Wait for Vercel deployment to complete for a commit.
branding:
  icon: clock
  color: blue
inputs:
  prod-url:
    description: Production url to wait for on master builds.
    required: true
  token:
    description: Vercel authorization token
    required: true
  timeout:
    description: The max time to run the action (in seconds)
    required: false
    default: "120"
outputs:
  url:
    description: The fully qualified deployment URL
runs:
  using: node12
  main: index.js
